In [1]:
# Import NumPy as its abbreviation 'np'

In [2]:
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
array_1D = np.array([1,2,3,4])
array_1D

array([1, 2, 3, 4])

In [8]:
# Create a 2-dimensional NumPy array using np.array()
array_2D = np.array([[1,2,3,4],[5,6,7,8]])
array_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Create a 3-dimensional Numpy array using np.array()
array_3D = np.array([[[1,2,3,4],[5,6,7,8]],[[11,13,14,15],[16,17,18,19]]])
array_3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 13, 14, 15],
        [16, 17, 18, 19]]])

In [20]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1D.shape , array_1D.ndim , array_1D.dtype , array_1D.size , type(array_1D)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [21]:
# Attributes of 2-dimensional array
# (shape,number of dimensions, data type, size and type)
array_2D.shape , array_2D.ndim , array_2D.dtype , array_2D.size , type(array_2D)

((2, 4), 2, dtype('int64'), 8, numpy.ndarray)

In [22]:
# Attributes of 3-dimensional array
# (shape,number of dimensions, data type, size and type)
array_3D.shape, array_3D.ndim , array_3D.dtype , array_3D.size ,type(array_3D)

((2, 2, 4), 3, dtype('int64'), 16, numpy.ndarray)

In [23]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [24]:
dataFrame_1 = pd.DataFrame(array_2D)
dataFrame_1

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [25]:
# Create an array of shape (10, 2) with only ones
onesArray = np.ones((10,2))
onesArray

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# Create an array of shape (7, 2, 3) of only zeros
zerosArray = np.zeros((7,2,3))
zerosArray

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
# Create an array within a range of 0 and 100 with step 3
randomArray_1 = np.arange(0,100,3)
randomArray_1
#arange() -> arange(start,stop,step,) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randomArray_2 = np.random.randint(0,10,(7,2))
randomArray_2
#np.random.randint(10,(7, 2)) – Create an array of 7x2 random integers between 0 and 9

array([[8, 6],
       [3, 5],
       [5, 2],
       [8, 5],
       [6, 6],
       [9, 8],
       [7, 3]], dtype=int32)

In [36]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomArray_3 = np.random.random((3, 5))
randomArray_3
#np.random.random((3, 5)) – Create a 3x5 array of random floats between 0 and 1


array([[0.15044721, 0.13661728, 0.94237006, 0.99453391, 0.85331864],
       [0.26401134, 0.10220236, 0.41150968, 0.05210204, 0.30813456],
       [0.3675736 , 0.35231356, 0.60845246, 0.89249556, 0.42088767]])

In [32]:
#np.random.rand(3, 5) – Same as random.random but with a simpler syntax
randomArray_4 = np.random.rand(3,5)
randomArray_4

array([[0.9864325 , 0.93358313, 0.07002392, 0.64717974, 0.86540422],
       [0.9388452 , 0.61892175, 0.05436742, 0.98135563, 0.43435618],
       [0.32054593, 0.01787214, 0.94477563, 0.89676003, 0.37799116]])

In [41]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
randomArray_5 = np.random.randint(0,10,(4,6))
randomArray_5

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
# Find the unique numbers in the array you just created
np.random.seed(42)
randomArray_6 = np.random.randint(1,10,(3,7))
randomArray_6 

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6],
       [5, 2, 8, 6, 2, 5, 1]], dtype=int32)

In [44]:
# np.unique(array) -> function returns the sorted unique elements of the input array
np.unique(randomArray_6)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [53]:
# Find the 0'th index of the latest array you created
elementAtZero = randomArray_6[0][0]
print(elementAtZero)

7


In [62]:
# Get the first 2 rows of latest array you created
#array slicing
#array[ start_row : end_row , start_col : end_col ]
randomArray_6[:2,:]

array([[7, 4, 8, 5, 7, 3, 7],
       [8, 5, 4, 8, 8, 3, 6]], dtype=int32)

In [64]:
# Get the first 2 values of the first 2 rows of the latest array
randomArray_6[:1,:2]

array([[7, 4]], dtype=int32)

In [65]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(0)
randomArray_7 = np.random.randint(0,10,(3,5))
onesArray_2 = np.ones((3,5))

In [70]:
# Add the two arrays together
outputArray = randomArray_7 + onesArray_2
outputArray

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [67]:
# Create another array of ones of shape (5, 3)
onesArray_3 = np.ones((5,3))

In [71]:
# Try add the array of ones and the other most recent array together
outputArray + onesArray_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [72]:
# Fix
outputArray + onesArray_3.T

array([[ 7.,  2.,  5.,  5.,  9.],
       [11.,  5.,  7.,  4.,  6.],
       [ 9.,  8., 10., 10.,  3.]])

In [73]:
# Create another array of ones of shape (3, 5)
onesArray_4 = np.ones((3,5))

In [74]:
# Subtract the new array of ones from the other most recent array
outputArray - onesArray_4

array([[5., 0., 3., 3., 7.],
       [9., 3., 5., 2., 4.],
       [7., 6., 8., 8., 1.]])

In [76]:
# Multiply the ones array with the latest array
outputArray * onesArray_4

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [77]:
# Take the latest array to the power of 2 using '**'
outputArray ** 2

array([[ 36.,   1.,  16.,  16.,  64.],
       [100.,  16.,  36.,   9.,  25.],
       [ 64.,  49.,  81.,  81.,   4.]])

In [78]:
# Do the same thing with np.square()
np.square(outputArray)

array([[ 36.,   1.,  16.,  16.,  64.],
       [100.,  16.,  36.,   9.,  25.],
       [ 64.,  49.,  81.,  81.,   4.]])

In [79]:
# Find the mean of the latest array using np.mean()
np.mean(outputArray)

np.float64(5.733333333333333)

In [80]:
# Find the maximum of the latest array using np.max()
np.max(outputArray)

np.float64(10.0)

In [81]:
outputArray

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [82]:
# Find the minimum of the latest array using np.min()
np.min(outputArray)

np.float64(1.0)

In [83]:
# Find the standard deviation of the latest array
np.std(outputArray)

np.float64(2.6449112566503166)

In [84]:
# Find the variance of the latest array
np.var(outputArray)

np.float64(6.995555555555556)

In [87]:
# Reshape the latest array to (3, 5, 1)
reshapedArray = np.reshape(outputArray,(3, 5, 1))
reshapedArray

array([[[ 6.],
        [ 1.],
        [ 4.],
        [ 4.],
        [ 8.]],

       [[10.],
        [ 4.],
        [ 6.],
        [ 3.],
        [ 5.]],

       [[ 8.],
        [ 7.],
        [ 9.],
        [ 9.],
        [ 2.]]])

In [88]:
reshapedArray.T

array([[[ 6., 10.,  8.],
        [ 1.,  4.,  7.],
        [ 4.,  6.,  9.],
        [ 4.,  3.,  9.],
        [ 8.,  5.,  2.]]])

In [90]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
randomArray_8 = np.random.randint(0,10,(3, 3))
randomArray_9 = np.random.randint(0,10,(3, 2))
randomArray_8 , randomArray_9

(array([[2, 3, 8],
        [1, 3, 3],
        [3, 7, 0]], dtype=int32),
 array([[1, 9],
        [9, 0],
        [4, 7]], dtype=int32))

In [92]:
# Perform a dot product on the two newest arrays you created
np.dot(randomArray_8,randomArray_9)

array([[61, 74],
       [40, 30],
       [66, 27]], dtype=int32)

In [93]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
randomArray_10 =  np.random.randint(0,10,(4, 3))
randomArray_11 =  np.random.randint(0,10,(4, 3))
randomArray_10 , randomArray_11

(array([[3, 2, 7],
        [2, 0, 0],
        [4, 5, 5],
        [6, 8, 4]], dtype=int32),
 array([[1, 4, 9],
        [8, 1, 1],
        [7, 9, 9],
        [3, 6, 7]], dtype=int32))

In [94]:
# Perform a dot product on the two newest arrays you created
np.dot(randomArray_10,randomArray_11)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [96]:
#Fix
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(randomArray_10,randomArray_11.T)

array([[ 74,  33, 102,  70],
       [  2,  16,  14,   6],
       [ 69,  42, 118,  77],
       [ 74,  60, 150,  94]], dtype=int32)

In [97]:
# Compare the two latest arrays with '>'
randomArray_11 > randomArray_10

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [98]:
# Compare the two arrays with '>='
randomArray_11 >= randomArray_10

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [99]:
# Find which elements of the first array are greater than 7
randomArray_10 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [100]:
# Which parts of each array are equal? (try using '==')
randomArray_11 == randomArray_10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [108]:
# Sort one of the arrays you just created in ascending order
#axis parameter:
#This parameter allows specifying the axis along which to sort.
#axis=None: Flattens the array and sorts all elements.
#axis=0: Sorts along the columns.
#axis=1: Sorts along the rows (default for 2D arrays).
sortedArray = np.sort(randomArray_10)
sortedArray

array([[2, 3, 7],
       [0, 0, 2],
       [4, 5, 5],
       [4, 6, 8]], dtype=int32)

In [109]:
# Sort the indexes of one of the arrays you just created
np.argsort(randomArray_11)

array([[1, 4, 9],
       [8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]], dtype=int32)

In [110]:
randomArray_11

array([[1, 4, 9],
       [8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]], dtype=int32)

In [111]:
# Sort the indexes of one of the arrays you just created
np.argsort(randomArray_11)

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]])

In [113]:
# Find the index with the maximum value in one of the arrays you've created
#np.argmax with no axis flattens the array and returns the index in the flattened version.
np.argmax(randomArray_11)

np.int64(2)

In [114]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(sortedArray)

np.int64(3)

In [115]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(randomArray_11,axis=1)

array([2, 0, 1, 2])

In [117]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(randomArray_11,axis=0)

array([0, 1, 1])

In [123]:
# Create an array with 10 evenly spaced numbers between 1 and 100
#linespace() -> generates an array of evenly spaced numbers over a defined interval
randomArray_12 = np.linspace(1, 100, 10)
randomArray_12

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [121]:
# Create an array of normally distributed random numbers
randomArray_13 = np.random.randn(3, 4)
randomArray_13

array([[-0.45688133, -1.05997576,  0.61495732,  1.42966077],
       [-0.21195226, -0.08033726,  0.40539778,  0.11860659],
       [ 1.25441407,  1.41910204, -0.74385608, -2.5174371 ]])